# ==== CONFIGURE =====
# Use a Node 16 base image
FROM node:16-alpine AS build
# Set the working directory to /app inside the container
WORKDIR /app
# Copy app files
COPY . .

ARG ARG_PORT
ENV PORT $ARG_PORT
ARG ARG_REACT_APP_FHIR_URL
ENV REACT_APP_FHIR_URL $ARG_REACT_APP_FHIR_URL
ARG ARG_REACT_APP_EXTRACTED_URL
ENV REACT_APP_EXTRACTED_URL $ARG_REACT_APP_EXTRACTED_URL
ARG ARG_REACT_APP_QUESTIONNAIRE_URL
ENV REACT_APP_QUESTIONNAIRE_URL $ARG_REACT_APP_QUESTIONNAIRE_URL
ARG ARG_REACT_APP_CQL_URL
ENV REACT_APP_CQL_URL $ARG_REACT_APP_CQL_URL
ARG ARG_REACT_APP_CDSHOOKS_URL
ENV REACT_APP_CDSHOOKS_URL $ARG_REACT_APP_CDSHOOKS_URL
ARG ARG_REACT_APP_TERMINOLOGY_URL
ENV REACT_APP_TERMINOLOGY_URL $ARG_REACT_APP_TERMINOLOGY_URL

ARG ARG_PUBLIC_URL
ENV PUBLIC_URL $ARG_PUBLIC_URL

ARG ARG_REACT_APP_DISPLAY_CLIENT_LOGO
ENV REACT_APP_DISPLAY_CLIENT_LOGO $ARG_REACT_APP_DISPLAY_CLIENT_LOGO

ARG ARG_REACT_APP_KEYCLOAK_URL
ENV REACT_APP_KEYCLOAK_URL $ARG_REACT_APP_KEYCLOAK_URL
ARG ARG_REACT_APP_REDIRECTURI
ENV REACT_APP_REDIRECTURI $ARG_REACT_APP_REDIRECTURI
ARG ARG_REACT_APP_KEYCLOAK_REALM
ENV REACT_APP_KEYCLOAK_REALM $ARG_REACT_APP_KEYCLOAK_REALM
ARG ARG_REACT_APP_KEYCLOAK_REALM_CLIENT_ID
ENV REACT_APP_KEYCLOAK_REALM_CLIENT_ID $ARG_REACT_APP_KEYCLOAK_REALM_CLIENT_ID
ARG ARG_REACT_APP_KEYCLOAK_FLOW
ENV REACT_APP_KEYCLOAK_FLOW $ARG_REACT_APP_KEYCLOAK_FLOW
ARG ARG_REACT_APP_KEYCLOAK_ONLOAD
ENV REACT_APP_KEYCLOAK_ONLOAD $ARG_REACT_APP_KEYCLOAK_ONLOAD
ARG ARG_REACT_APP_KEYCLOAK_CHECKSSO_LOGIN_IFRAME
ENV REACT_APP_KEYCLOAK_CHECKSSO_LOGIN_IFRAME $ARG_REACT_APP_KEYCLOAK_CHECKSSO_LOGIN_IFRAME
ARG ARG_REACT_APP_KEYCLOAK_CHECKSSO_FALLBACK
ENV REACT_APP_KEYCLOAK_CHECKSSO_FALLBACK $ARG_REACT_APP_KEYCLOAK_CHECKSSO_FALLBACK
ARG ARG_REACT_APP_KEYCLOAK_PKCE_METHOD
ENV REACT_APP_KEYCLOAK_PKCE_METHOD $ARG_REACT_APP_KEYCLOAK_PKCE_METHOD

# ==== BUILD =====
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc npm ci --force
# ==== RUN =======
# Run before launching the server to make sure the environment variables are taken into account
RUN npm run build

# Production Stage
FROM nginx:stable-alpine AS production

ARG ARG_PUBLIC_URL
ENV PUBLIC_URL $ARG_PUBLIC_URL
# Install envsubst
RUN apk add --no-cache gettext

# Write nginx template
RUN cat <<'EOF' > /tmp/nginx.template
server {
    listen 80;
    server_name sphinx;

     # Ensure /sphinx (no slash) works
    location = ${PUBLIC_URL} {
        return 301 ${PUBLIC_URL}/;
    }

    # Serve React SPA under /sphinx/
    location ${PUBLIC_URL}/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ ${PUBLIC_URL}/index.html;
    }
}
EOF

# Expand ${PUBLIC_URL} inside the template
RUN envsubst '${PUBLIC_URL}' < /tmp/nginx.template > /etc/nginx/conf.d/default.conf

COPY --from=build /app/build /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]