services:
  sphinx:
    image: docker.registry.fyrstain.com/product/sphinx/front:2.2.0
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        ARG_PORT: ${PORT}
        ARG_REACT_APP_FHIR_URL: ${REACT_APP_FHIR_URL}
        ARG_REACT_APP_EXTRACTED_URL: ${REACT_APP_EXTRACTED_URL}
        ARG_REACT_APP_QUESTIONNAIRE_URL: ${REACT_APP_QUESTIONNAIRE_URL}
        ARG_REACT_APP_CDSHOOKS_URL: ${REACT_APP_CDSHOOKS_URL}
        ARG_REACT_APP_TERMINOLOGY_URL: ${REACT_APP_TERMINOLOGY_URL}
        ARG_PUBLIC_URL: ${PUBLIC_URL}
        ARG_REACT_APP_DISPLAY_CLIENT_LOGO: ${REACT_APP_DISPLAY_CLIENT_LOGO}
        ARG_REACT_APP_KEYCLOAK_URL: ${REACT_APP_KEYCLOAK_URL}
        ARG_REACT_APP_REDIRECTURI: ${REACT_APP_REDIRECTURI}
        ARG_REACT_APP_KEYCLOAK_REALM: ${REACT_APP_KEYCLOAK_REALM}
        ARG_REACT_APP_KEYCLOAK_REALM_CLIENT_ID: ${REACT_APP_KEYCLOAK_REALM_CLIENT_ID}
        ARG_REACT_APP_KEYCLOAK_FLOW: ${REACT_APP_KEYCLOAK_FLOW}
        ARG_REACT_APP_KEYCLOAK_ONLOAD: ${REACT_APP_KEYCLOAK_ONLOAD}
        ARG_REACT_APP_KEYCLOAK_CHECKSSO_LOGIN_IFRAME: ${REACT_APP_KEYCLOAK_CHECKSSO_LOGIN_IFRAME}
        ARG_REACT_APP_KEYCLOAK_CHECKSSO_FALLBACK: ${REACT_APP_KEYCLOAK_CHECKSSO_FALLBACK}
        ARG_REACT_APP_KEYCLOAK_PKCE_METHOD: ${REACT_APP_KEYCLOAK_PKCE_METHOD}
    secrets:
        - npmrc
    env_file: ".env"
    environment:
      - REACT_APP_FHIR_URL=${REACT_APP_FHIR_URL}
      - REACT_APP_QUESTIONNAIRE_URL=${REACT_APP_QUESTIONNAIRE_URL}
      - REACT_APP_EXTRACTED_URL=${REACT_APP_EXTRACTED_URL}
      - REACT_APP_CQL_URL=${REACT_APP_CQL_URL}
      - REACT_APP_CDSHOOKS_URL=${REACT_APP_CDSHOOKS_URL}
      - REACT_APP_TERMINOLOGY_URL=${REACT_APP_TERMINOLOGY_URL}
      - REACT_APP_REDIRECTURI=${REACT_APP_REDIRECTURI}
    ports:
      - "${PORT}:3000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://sphinx:3000/Home"]
      timeout: "300s"
      interval: "30s"
      retries: 3
      start_period: "15s"
    restart: unless-stopped


networks:
  host:
    external: true

secrets:
  npmrc:
    file: ./.npmrc