version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.7.3
    container_name: keycloak
    command: start-dev --import-realm
    volumes:
      - ./keycloak/data:/opt/keycloak/data/h2
      - ./Keycloak/import:/opt/keycloak/data/import
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "${KEYCLOAK_PORT}:8080"
    restart: unless-stopped

networks:
  host:
    external: true
