version: '3.8'
services:
  sphinx:
    image: docker.registry.fyrstain.com/software/sphinx/front:latest
    environment:
      - REACT_APP_FHIR_URL=${REACT_APP_FHIR_URL}
      - REACT_APP_QUESTIONNAIRE_URL=${REACT_APP_QUESTIONNAIRE_URL}
      - REACT_APP_EXTRACTED_URL=${REACT_APP_EXTRACTED_URL}
      - REACT_APP_CQL_URL=${REACT_APP_CQL_URL}
      - REACT_APP_REDIRECTURI=http://sphinx:3000/
    ports:
      - "${PORT}:${PORT}"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://sphinx:3000/Home" ]
      timeout: "300s"
      interval: "30s"
      retries: 3
      start_period: "15s"
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: keycloak
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --import-realm
    volumes:
      - ./keycloak/data:/opt/keycloak/data/h2
      - ./Keycloak/import:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "${KEYCLOAK_PORT}:8080"
    restart: unless-stopped

networks:
  host:
    external: true
