name: Publish snapshot

on:
  push:
    branches: [feature]

permissions:
  contents: read

jobs:
  snapshot:
    uses: Fyrstain/github-workflows/.github/workflows/react-snapshot.yml@1.0.0
    with:
      node_version: '24'
      working_directory: .
      image_name: product/sphinx/front
      docker_context: .
      dockerfile: Dockerfile
      image_tag: ''
      build_args: |
        ARG_PORT=3000
        ARG_REACT_APP_FHIR_URL=http://localhost:8080/fhir
        ARG_REACT_APP_EXTRACTED_URL=http://localhost:8080/fhir
        ARG_REACT_APP_QUESTIONNAIRE_URL=http://localhost:8080/fhir
        ARG_REACT_APP_CDSHOOKS_URL=http://localhost:8080/fhir
        ARG_REACT_APP_TERMINOLOGY_URL=http://localhost:8080/fhir
        ARG_PUBLIC_URL=http://localhost:3000/sphinx/
        ARG_REACT_APP_DISPLAY_CLIENT_LOGO=false
        ARG_REACT_APP_KEYCLOAK_URL=http://localhost:8999/
        ARG_REACT_APP_REDIRECTURI=http://localhost:3000/
        ARG_REACT_APP_KEYCLOAK_REALM=demo
        ARG_REACT_APP_KEYCLOAK_REALM_CLIENT_ID=pandora-demo
        ARG_REACT_APP_KEYCLOAK_FLOW=standard
        ARG_REACT_APP_KEYCLOAK_ONLOAD=check-sso
        ARG_REACT_APP_KEYCLOAK_CHECKSSO_LOGIN_IFRAME=false
        ARG_REACT_APP_KEYCLOAK_CHECKSSO_FALLBACK=false
        ARG_REACT_APP_KEYCLOAK_PKCE_METHOD=S256
    secrets:
      registry: ${{ secrets.NEXUS_REGISTRY }}
      username: ${{ secrets.NEXUS_USERNAME }}
      password: ${{ secrets.NEXUS_PASSWORD }}
      npmrc: ${{ secrets.NPMRC }}
